name: Tests

on:
  push:
    tags:
      - "*"

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]

    steps:
      - uses: actions/checkout@v2

        # - name: Setup git credentials
        #   uses: fusion-engineering/setup-git-credentials@v2
        #   with:
        #     credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v1
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Tox
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: pip install tox

      - name: Cache Tox
        uses: actions/cache@v1
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Cache Molecule
        uses: actions/cache@v1
        with:
          path: ~/.cache/molecule
          key: ${{ runner.os }}-molecule-${{ hashFiles('**/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-molecule-

      - name: Run Tox
        run: tox
